### PR TITLE
ISLANDORA-1964: Fix bug and build

### PR DESCRIPTION
**Pull request by adam-vessey**
**JIRA Ticket**: [ISLANDORA-1964](https://jira.duraspace.org/browse/ISLANDORA-1964)

# What does this Pull Request do?

Use the passed `stream` in `ca.upei.roblib.fedora.servletfilter.DrupalAuthModule.getParsedConfig(InputStream stream)`, and adjust the build process such that we can build against older versions of Fedora (at least 3.6.2, 3.7.0, 3.7.1 and 3.8.1).

# What's new?

Nothing.

# How should this be tested?

The artifact builds; otherwise, just regression testing, making sure things work nominally.

# Additional Notes:

Bug itself is fairly minor... discovered in the [initial work](https://github.com/Islandora/islandora_drupal_filter/pull/19) for [ISLANDORA-1940](https://jira.duraspace.org/browse/ISLANDORA-1940). This bug wouldn't affect normal running of the code, as the `getConfig()` call would have resulted in the default call (without the parameter being passed).

* **Does this change require documentation to be updated?** No.
* **Does this change add any new dependencies?** No.
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No.
* **Could this change impact execution of existing code?** No.

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by adam-vessey** [comment]
Just for convenience, the comparison, without the huge whitespace change from formatting the `pom.xml`: https://github.com/Islandora/islandora_drupal_filter/compare/0602ce6...adam-vessey:builds

**Comment by willtp87** [comment]
I think this pull is good to merge.

**Comment by DiegoPino** [comment]
@willtp87 @adam-vessey wanted to ask you about that.  This module is not under release workflow (versioning, tagging) but affects releases for sure. Should we talk about that before merging? (code is good, its not about the quality of the code) Just because Vagrant, testing and even deployment depends on this one very very deeply. Pinging @manez and @dannylamb also since i think we already had that talk in the agenda.

**Comment by willtp87** [comment]
@DiegoPino Sounds like a good discussion for the committers call.

**Comment by jordandukart** [comment]
Bump @DiegoPino @Islandora/7-x-1-x-committers

**Comment by DiegoPino** [comment]
@jordandukart merge will happen somewhere today. I will create first the 7.x-1.9 branch, then merge this one, then create a  new 7.x based on master and make master the default. Is any @Islandora/7-x-1-x-committers depending explicitly on "master"  being named "master"?

**Comment by manez** [comment]
@ruebot this is following up on some discussions from Committers Calls and got the 👍  there

**Comment by DiegoPino** [comment]
@ruebot that is not what we agreed on the last committers call. We will have release branches for drupal filter.

**Comment by DiegoPino** [comment]
@adam-vessey can you point me to where the issue with the compiling was/why//and how that was fixed?
Pre-this pull compiling is failing bad which means i can't possible make a release of the jar files on 7.x-1.9 without merging this into 7.x-1.9. last release was in 2013 so i'm pretty sure lots has changed since then,

https://github.com/Islandora/islandora_drupal_filter/pull/20/commits/0cd330b6b21180dc0f97602bcbf0f35f659f753e  are those the important bits?

**Comment by adam-vessey** [comment]
@DiegoPino: Yeah, https://github.com/Islandora/islandora_drupal_filter/pull/20/commits/0cd330b6b21180dc0f97602bcbf0f35f659f753e was just fixing the build (plus a couple little whitespace changes that sneaked in).

**Comment by DiegoPino** [comment]
@adam-vessey ok. To be able to roll a release (the 28th), this is what i will do: I will remove the just created 7.x-1.9 branch, will merge this pull request into master and will then re-create 7.x-1.9 which will include this merged fix to be able to keep that one froze (at last). Will then merge to master that open readme #21 pull request and will create a new 7.x -which will become the new master-. Then the 28th i will publish a bunch of jar files, one for each version this thing runs on.
Lastly, i think we should put this in maven? Any thoughts on that?

**Comment by DiegoPino** [comment]
@ruebot i encourage to use your veto if you think it applies and for sure i will bring this talk back to our call tomorrow, won't touch a piece of software in the meantime. But this is not about versioning / way of implementing versioning.If the branch name matches a release version of islandora does not mean that the version of our drupal filter is the name of the branch. Not sure if that is clear? Can't even imagine having a "master version" for every project that runs on "master" branches anyway.

This is about making sure our release (Islandora, php piece of that) is tested and deployed on a single, tested released drupal filter version, which is one of the corner stones, *as tuque is also*, of the islandora ecosystem. Whatever that "versioning" is, which i will make sure is discussed, i want to make sure that what is tested with/during a release stays stable and does not change after that for that release.

Thanks for the link to our rights. Attaching also the one about [responsibilities ](https://github.com/Islandora/islandora/wiki/Islandora-Committers#responsibilities) because again, during my duties as release manager you have objections on decision and topics discussed during committers calls and instead of bringing them to that instance, an instance made for that, you come as supervisor using this or IRC. I'm not longer cool with that and honestly getting tired of this and dictating over other people's behaviour from the outside seems unfair. There are many ways of doing things in Software projects, and even if your way is correct and was successful many times, it is not the only correct way. Also, if my way is not correct, i'm completely entitled to make mistakes. Open Source Software belongs to communities, not to individuals as you an me. We come and go, communities, the concept, stays.

**Comment by dannylamb** [comment]
@ruebot If you feel the need, you are within your rights to re-raise the issue and make an agenda item for the next release call, which is today.  But I'm not sure how much traction you'll get since this was decided upon at the last release meeting.

And there is no need to start tossing rights and responsibilities links at each other, gentlemen.  If anything, you should both be reading https://islandora.ca/codeofconduct.  And in particular:

> We are respectful. Everyone can make a valuable contribution to Islandora, and all contributions are welcome. We may not always agree. When we disagree, we do this in a polite and professional manner. When frustrated, we back away and look for good intentions, not reasons to be more frustrated. When we see a flaw in a contribution, we offer guidance on how to fix it.

**Pull request merged**
